export const ListAgent = [
  {
    id: 1,
    name: 'Nguyễn Ngọc Thuận',
    phone: '0931695423',
    mail: 'ngocthuandn1998@gmail.com',
    facebook: 'https://www.facebook.com/ngocthuan.nguyen.54584',
    consultingArea: 'Quận Hải Châu',
  },
  {
    id: 2,
    name: 'Bùi Quốc Tấn',
    phone: '0354010680',
    mail: 'Tanbui@gmail.com',
    facebook: 'https://www.facebook.com/scarringinlife',
    consultingArea: 'Quận Thanh Khê',
  },
  {
    id: 3,
    name: 'Nguyễn Tiến Đạt',
    phone: '0912433179',
    mail: 'TienDat@gmail.com',
    facebook: 'https://www.facebook.com/ngocthuan.nguyen.54584',
    consultingArea: 'Quận Liên Chiểu',
  },
  {
    id: 4,
    name: 'Lê Tuấn Anh',
    phone: '0974616210',
    mail: 'anhlt@gmail.com',
    facebook: 'https://www.facebook.com/letuananh2313 ',
    consultingArea: 'Quận Cẩm Lệ',
  },
  {
    id: 5,
    name: 'Trần Anh Kiệt',
    phone: '0379366250',
    mail: 'anhkiet@gmail.com',
    facebook: 'https://www.facebook.com/tak269',
    consultingArea: 'Quận Ngũ Hành Sơn',
  },
  {
    id: 6,
    name: 'Lê Quốc Tài',
    phone: '0932599100',
    mail: 'Taile@gmail.com',
    facebook: 'https://www.facebook.com/ngocthuan.nguyen.54584',
    consultingArea: 'Quận Sơn Trà',
  },
]
